- name: enable pacemaker resources for {{service}}
  command: pcs resource enable {{item}}
  with_items: resources
- name: wait for {{service}} resources to start
  shell: >
    while pcs status xml |
        xmllint --xpath '//resource[@id = "{{item}}" and @role = "Stopped"]' -; do
      sleep 1
    done
  with_items: resources
  when: wait

