# Start a list of Pacemaker resources
#
# This uses `pcs enable` to start a list of specific Pacemaker
# resources, then waits for those resources to exit the `Stopped`
# role.
- name: enable pacemaker resources for {{service}}
  command: pcs resource enable {{item}}
  with_items: resources
  run_once: true
- name: wait for {{service}} resources to start
  shell: |
    while pcs status xml |
        xmllint --xpath '/crm_mon/resources/*[@id = "{{item}}" and (@role = "Stopped" or resource/@role = "Stopped")]' -; do
      sleep 1
    done
  with_items: resources
  when: wait
  run_once: true
