# Stop Pacemaker resources matching the given prefix string
#
# This looks for resources matching the given `resource_prefix` string, calls
# `pcs disable` on the result, and then waits for those resources to exit the
# `Started` role.
- name: get list of {{resource_prefix}} resources
  shell: |
    pcs status xml |
    xmllint --xpath '/crm_mon/resources/*[starts-with(@id, "{{resource_prefix}}")]/@id' -  |
    tr ' ' '\n' |
    cut -f2 -d'"' |
    grep -v '^$'
  run_once: true
  register: resources
- name: disable {{resource_prefix}} resource
  command: pcs resource disable {{item}}
  with_items: resources.stdout_lines
  when: item not in resource_exclude
  run_once: true
- name: wait for {{resource_prefix}} resources to stop
  shell: |
    while pcs status xml |
        xmllint --xpath '/crm_mon/resources/*[@id = "{{item}}" and (@role != "Stopped" or resource/@role != "Stopped")]' -; do
      sleep 1
    done
  run_once: true
  with_items: resources.stdout_lines
  when: item not in resource_exclude
