# Start Pacemaker resources matching the given prefix string
#
# This looks for resources matching the given `resource_prefix` string, calls
# `pcs enable` on the result, and then waits for those resources to exit the
# `Stopped` role.
- name: get list of {{resource_prefix}} resources
  shell: |
    pcs status xml |
    xmllint --xpath '/crm_mon/resources/*[starts-with(@id, "{{resource_prefix}}")]/@id' -  |
    tr ' ' '\n' |
    cut -f2 -d'"' |
    grep -v '^$'
  run_once: true
  register: resources
- name: enable {{resource_prefix}} resource
  command: pcs resource enable {{item}}
  with_items: resources.stdout_lines
  when: resource_exclude is not defined or resource_exclude not in item
  run_once: true
- name: wait for {{resource_prefix}} resources to start
  shell: |
    while pcs status xml |
        xmllint --xpath '//resource[@id = "{{item}}" and @role = "Stopped"]' -; do
      sleep 1
    done
  run_once: true
  with_items: resources.stdout_lines
  when: resource_exclude is not defined or resource_exclude not in item
