- name: stop pacemaker resources
  shell: >
    pcs status xml |
    xmllint --xpath '/crm_mon/resources/*[starts-with(@id, "{{resource_prefix}}")]/@id' -  |
    tr ' ' '\n' |
    cut -f2 -d'"' |
    xargs -n1 pcs resource disable
  run_once: true
- name: wait for pacemaker resources to stop
  shell: >
    while pcs status xml |
        xmllint --xpath '//resource[starts-with(@id, "{{resource_prefix}}") and @role = "Started"]' -; do
      sleep 1
    done
  run_once: true

