# # Upgrade Neutron
#
# This playbook updates OpenStack Neutron, using a process that is
# largely similar to what we used for Glance.  However, for Neutron we
# need to ensure that Pacemaker doesn't run the `neutron-ovs-cleanup`
# and `neutron-netns-cleanup` scripts, which will interrupt network
# connectivity to any running Nova servers, so we `pcs unmanage` the
# corresponding resources first.
#
- hosts: controller
  tags:
    - disable
    - disable-neutron
  pre_tasks:
    - name: prevent pacemaker from managing cleanup actions
      command: pcs resource unmanage {{item}}
      with_items:
        - neutron-ovs-cleanup-clone
        - neutron-netns-cleanup-clone
  roles:
    - role: pcs-stop-prefix
      resource_prefix: neutron
      resource_exclude:
        - neutron-ovs-cleanup-clone
        - neutron-netns-cleanup-clone
        - neutron-scale-clone

- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-neutron*
        - python-neutron*
        - dnsmasq
        - openvswitch

# ## Bugfixes
#
# ### BZ 1250156: openstack-neutron depends on python-oslo-config
#
# - <https://bugzilla.redhat.com/show_bug.cgi?id=1250156>
#
- hosts: controller
  tags:
    - bugfix
    - bz1250156
  tasks:
    - name: "BZ 1250156: openstack-neutron depends on python-oslo-config"
      yum: name={{item}} state=latest
      with_items:
        - python-oslo-config

# ### BZ 1250160: openstack-neutron depends on python-oslo-i18n
#
# - <https://bugzilla.redhat.com/show_bug.cgi?id=1250160>
#
- hosts: controller
  tags:
    - bugfix
    - bz1250160
  tasks:
    - name: "BZ 1250160: openstack-neutron depends on python-oslo-i18n"
      yum: name={{item}} state=latest
      with_items:
        - python-oslo-i18n

# ### BZ 1250164: openstack-neutron depends on python-oslo-db
#
# - <https://bugzilla.redhat.com/show_bug.cgi?id=1250164>
#
- hosts: controller
  tags:
    - bugfix
    - bz1250164
  tasks:
    - name: "BZ 1250164: openstack-neutron depends on python-oslo-db"
      yum: name={{item}} state=latest
      with_items:
        - python-oslo-db

# ### BZ 1250166: openstack-neutron depends on python-oslo-messaging
#
# - <https://bugzilla.redhat.com/show_bug.cgi?id=1250166>
#
- hosts: controller
  tags:
    - bugfix
    - bz1250166
  tasks:
    - name: "BZ 1250166: openstack-neutron depends on python-oslo-messaging"
      yum: name={{item}} state=latest
      with_items:
        - python-oslo-messaging

# ### BZ 1246599: neutron requires oslo_rootwrap
#
# - <https://bugzilla.redhat.com/show_bug.cgi?id=1246599>
#
- hosts: controller
  tags:
    - bugfix
    - bz1246599
  tasks:
    - name: "BZ 1246599: neutron requires oslo_rootwrap"
      yum: name={{item}} state=latest
      with_items:
        - python-oslo-rootwrap

# ## Reload systemd
#
# Package updates may include new systemd unit files, so we make sure
# that systemd is aware of any updated files.
#
- include: reload-systemd.yml

# ## Update database schema
#
- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service neutron --update
      run_once: true

# ## Update Neutron rootwrap configuration
#
# According to the [Neutron upgrade notes][], the rootwrap `dhcp.filter`
# configuration needs to be edited after upgrading from earlier
# releases.
#
# [neutron upgrade notes]: https://wiki.openstack.org/wiki/ReleaseNotes/Kilo#Upgrade_Notes_6
- hosts: controller
  tasks:
    - name: fix neutron dnsmasq rootwrap filter
      command: >
        sed -i '{{item}}' /usr/share/neutron/rootwrap/dhcp.filters
      with_items:
        - '/^dnsmasq:/ s/: .*/: CommandFilter, dnsmasq, root/'
      run_once: true

# ## Restart Neutron services
#
# We restart all of the Neutron services, and we return the cleanup
# resources to management by Pacemaker.
- hosts: controller
  tags:
    - enable
    - enable-neutron
  roles:
    - role: pcs-start-prefix
      resource_prefix: neutron
      resource_exclude:
        - neutron-ovs-cleanup-clone
        - neutron-netns-cleanup-clone
        - neutron-scale-clone
  tasks:
    - name: allow pacemaker to manage cleanup actions
      command: pcs resource manage {{item}}
      with_items:
        - neutron-ovs-cleanup-clone
        - neutron-netns-cleanup-clone
