# # Upgrade Glance
#
# This playbook ugrades the OpenStack Glance service.  We start by
# disabling all Glance services across the cluster.
#
- hosts: controller
  tags:
    - disable
    - disable-glance
  roles:
    - role: pcs-stop-prefix
      resource_prefix: glance

# With Glance offline, we are able to upgrade the relevant packages.
#
- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-glance*
        - python-glance*

# Package updates may include new systemd unit files, so we make sure
# that systemd is aware of any updated files.
#
- include: reload-systemd.yml

# We need to update the database schema to the version expected by the
# updated packages.
#
- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service glance --update
      run_once: true

# Finally, we restart Glance services across the cluster.
- hosts: controller
  tags:
    - enable
    - enable-glance
  roles:
    - role: pcs-start-prefix
      resource_prefix: glance
