- hosts: controller
  tags:
    - disable
    - disable-neutron
  roles:
    - role: pcs-stop-prefix
      resource_prefix: neutron

- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-neutron*
        - python-neutron*
        - dnsmasq
        - openvswitch

- hosts: controller
  tags:
    - bugfix
    - bz1250156
    - bz1250160
    - bz1250164
    - bz1250166
    - bz1250219
    - packages
  tasks:
    - name: "BZ 1250156,1250160,1250164,1250166,1250219: fix neutron dependencies"
      yum: name={{item}} state=latest
      with_items:
        - python-oslo-db
        - python-oslo-messaging
        - python-oslo-i18n
        - python-oslo-config
        - python-oslo-rootwrap

- include: reload-systemd.yml

- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service neutron --update
      run_once: true

# ## Update Neutron rootwrap configuration
#
# According to the [Kilo release notes][], the rootwrap `dhcp.filter`
# configuration needs to be edited after upgrading from earlier
# releases.
#
# - <https://wiki.openstack.org/wiki/ReleaseNotes/Kilo#Upgrade_Notes_6>
- hosts: controller
  tasks:
    - name: fix neutron dnsmasq rootwrap filter
      command: >
        sed -i '{{item}}' /usr/share/neutron/rootwrap/dhcp.filters
      with_items:
        - '/^dnsmasq:/ s/: .*/: CommandFilter, dnsmasq, root/'
      run_once: true

- hosts: controller
  tags:
    - enable
    - enable-neutron
  pre_tasks:
    - name: kill dnsmasq
      command: pkill dnsmasq
      ignore_errors: true
  roles:
    - role: pcs-start-prefix
      resource_prefix: neutron
