- hosts: controller
  tags:
    - disable
    - disable-glance
  roles:
    - role: pcs-stop-prefix
      resource_prefix: glance

- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-glance*
        - python-glance*

- include: reload-systemd.yml

- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service glance --update
      run_once: true

- hosts: controller
  tags:
    - enable
    - enable-glance
  roles:
    - role: pcs-start-prefix
      resource_prefix: glance
