- hosts: controller
  tags:
    - disable
    - disable-nova
  roles:
    - role: pcs-stop-prefix
      resource_prefix: openstack-nova

- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-nova*
        - python-nova*

# ### BZ 1250589: openstack-nova requires python-oslo-config
- hosts: controller
  tags:
    - bugfix
    - bz1250589
  tasks:
    - name: "BZ 1250589: openstack-nova requires python-oslo-config"
      yum: name=python-oslo-config state=latest

# ### BZ 1250594: openstack-nova requires python-oslo-utils
- hosts: controller
  tags:
    - bugfix
    - bz1250594
  tasks:
    - name: "BZ 1250594: openstack-nova requires python-oslo-utils"
      yum: name=python-oslo-utils state=latest

# ### BZ 1250597: openstack-nova requires python-oslo-i18n
- hosts: controller
  tags:
    - bugfix
    - bz1250597
  tasks:
    - name: "BZ 1250597: openstack-nova requires python-oslo-i18n"
      yum: name=python-oslo-i18n state=latest

# ### BZ 1250599: openstack-nova requires python-oslo-serialization
- hosts: controller
  tags:
    - bugfix
    - bz1250599
  tasks:
    - name: "BZ 1250599: openstack-nova requires python-oslo-serialization"
      yum: name=python-oslo-serialization state=latest

# ### BZ 1250604: openstack-nova requires python-oslo-messaging
- hosts: controller
  tags:
    - bugfix
    - bz1250604
  tasks:
    - name: "BZ 1250604: openstack-nova requires python-oslo-messaging"
      yum: name=python-oslo-messaging state=latest

# ### BZ 1250606: openstack-nova requires python-oslo-db
- hosts: controller
  tags:
    - bugfix
    - bz1250606
  tasks:
    - name: "BZ 1250606: openstack-nova requires python-oslo-db"
      yum: name=python-oslo-db state=latest

# ### BZ 1250609: openstack-nova requires python-oslo-rootwrap
- hosts: controller
  tags:
    - bugfix
    - bz1250609
  tasks:
    - name: "BZ 1250609: openstack-nova requires python-oslo-rootwrap"
      yum: name=python-oslo-rootwrap state=latest

# ### BZ 1250621: openstack-nova requires upgraded python-neutronclient
- hosts: controller
  tags:
    - bugfix
    - bz1250621
  tasks:
    - name: "BZ 1250621: openstack-nova requires upgraded python-neutronclient"
      yum: name=python-neutronclient state=latest

# ### BZ 1246638: novncproxy requires upgraded websockify
#
# The novncproxy service in OSP-7 requires at least version 0.6.0 of
# the python-websockify package, but does not specify this requirement
# as a package dependency.
#
# This task ensures that a functional version of python-websockify is
# installed.
#
# - <http://bugzilla.redhat.com/1246638>
#
- hosts: controller
  tags:
    - nova
    - bugfix
    - bz1246638
    - packages
  tasks:
    - name: "BZ 1246638: novncproxy requires upgraded websockify"
      yum: name=python-websockify state=latest

- include: reload-systemd.yml

- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service nova --update
      run_once: true
    - name: migrate nova flavor data
      command: >
        runuser -u nova -- nova-manage db
        migrate_flavor_data {{migrate_flavor_max_instance|default('100')}}
      run_once: true

- hosts: controller
  tags:
    - config
    - config-nova
  tasks:
    - name: set api caps on controller
      command: >
        crudini --set /etc/nova/nova.conf upgrade_levels {{item}} juno
      with_items:
        - compute

- hosts: controller
  tags:
    - enable
    - enable-nova
  roles:
    - role: pcs-start-prefix
      resource_prefix: openstack-nova
