- hosts: controller
  tags:
    - disable
    - disable-cinder
  roles:
    - role: pcs-stop-prefix
      resource_prefix: cinder

- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-cinder*
        - python-cinder*

- include: reload-systemd.yml

- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service cinder --update
      run_once: true

- hosts: controller
  tags:
    - enable
    - enable-cinder
  roles:
    - role: pcs-start-prefix
      resource_prefix: cinder
