# # Upgrade Nova
#
# This playbook updates OpenStack Nova on the controllers.
#
- hosts: controller
  tags:
    - disable
    - disable-nova
  roles:
    - role: pcs-stop-prefix
      resource_prefix: openstack-nova

- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-nova*
        - python-nova*

# ## Bugfixes
#
# ### BZ 1250589: openstack-nova requires python-oslo-config
#
# - <http://bugzilla.redhat.com/1250589>
- hosts: controller
  tags:
    - bugfix
    - bz1250589
  tasks:
    - name: "BZ 1250589: openstack-nova requires python-oslo-config"
      yum: name=python-oslo-config state=latest

# ### BZ 1250594: openstack-nova requires python-oslo-utils
#
# - <http://bugzilla.redhat.com/1250594>
- hosts: controller
  tags:
    - bugfix
    - bz1250594
  tasks:
    - name: "BZ 1250594: openstack-nova requires python-oslo-utils"
      yum: name=python-oslo-utils state=latest

# ### BZ 1250597: openstack-nova requires python-oslo-i18n
#
# - <http://bugzilla.redhat.com/1250597>
- hosts: controller
  tags:
    - bugfix
    - bz1250597
  tasks:
    - name: "BZ 1250597: openstack-nova requires python-oslo-i18n"
      yum: name=python-oslo-i18n state=latest

# ### BZ 1250599: openstack-nova requires python-oslo-serialization
#
# - <http://bugzilla.redhat.com/1250599>
- hosts: controller
  tags:
    - bugfix
    - bz1250599
  tasks:
    - name: "BZ 1250599: openstack-nova requires python-oslo-serialization"
      yum: name=python-oslo-serialization state=latest

# ### BZ 1250604: openstack-nova requires python-oslo-messaging
#
# - <http://bugzilla.redhat.com/1250604>
- hosts: controller
  tags:
    - bugfix
    - bz1250604
  tasks:
    - name: "BZ 1250604: openstack-nova requires python-oslo-messaging"
      yum: name=python-oslo-messaging state=latest

# ### BZ 1250606: openstack-nova requires python-oslo-db
#
# - <http://bugzilla.redhat.com/1250606>
- hosts: controller
  tags:
    - bugfix
    - bz1250606
  tasks:
    - name: "BZ 1250606: openstack-nova requires python-oslo-db"
      yum: name=python-oslo-db state=latest

# ### BZ 1250609: openstack-nova requires python-oslo-rootwrap
#
# - <http://bugzilla.redhat.com/1250609>
- hosts: controller
  tags:
    - bugfix
    - bz1250609
  tasks:
    - name: "BZ 1250609: openstack-nova requires python-oslo-rootwrap"
      yum: name=python-oslo-rootwrap state=latest

# ### BZ 1250621: openstack-nova requires upgraded python-neutronclient
#
# - <http://bugzilla.redhat.com/1250621>
- hosts: controller
  tags:
    - bugfix
    - bz1250621
  tasks:
    - name: "BZ 1250621: openstack-nova requires upgraded python-neutronclient"
      yum: name=python-neutronclient state=latest

# ### BZ 1246638: novncproxy requires upgraded websockify
#
# The novncproxy service in OSP-7 requires at least version 0.6.0 of
# the python-websockify package, but does not specify this requirement
# as a package dependency.
#
# This task ensures that a functional version of python-websockify is
# installed.
#
# - <http://bugzilla.redhat.com/1246638>
#
- hosts: controller
  tags:
    - nova
    - bugfix
    - bz1246638
    - packages
  tasks:
    - name: "BZ 1246638: novncproxy requires upgraded websockify"
      yum: name=python-websockify state=latest

# ## Reload systemd
#
# Package updates may include new systemd unit files, so we make sure
# that systemd is aware of any updated files.
#
- include: reload-systemd.yml

# ## Database updates
#
# In addition to the schema upgrade, Nova also needs to perform some
# data migrations as part of the OSP 6 -> OSP 7 upgrade, as documented
# in the [Nova upgrade notes][].
#
# [nova upgrade notes]: https://wiki.openstack.org/wiki/ReleaseNotes/Kilo#Upgrade_Notes_2
#
- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service nova --update
      run_once: true
    - name: migrate nova flavor data
      command: >
        runuser -u nova -- nova-manage db
        migrate_flavor_data {{migrate_flavor_max_instance|default('100')}}
      run_once: true

# ## Set API limits
#
# We want to ensure that our OSP-7 controllers are compatible with our
# OSP-6 compute nodes.  Once the upgrade of both the controllers and
# compute nodes is complete we will remove these API limits.
#
- hosts: controller
  tags:
    - config
    - config-nova
  tasks:
    - name: set api caps on controller
      command: >
        crudini --set /etc/nova/nova.conf upgrade_levels {{item}} juno
      with_items:
        - compute

# ## Restart Nova services
#
# Lastly we restart Nova services on the controllers.
- hosts: controller
  tags:
    - enable
    - enable-nova
  roles:
    - role: pcs-start-prefix
      resource_prefix: openstack-nova
