- hosts: controller
  serial: 1
  tasks:
    - name: get local pacemaker node name
      command: crm_node -n
      register: crm_node
    - name: stop galera from running on this node
      command: pcs resource ban galera-master {{crm_node.stdout}}
    - name: wait for galera to stop
      shell: >
        while pcs status xml |
            xmllint --xpath '//resource[@id = "galera"]/node[@name="{{crm_node.stdout}}"]' -; do
          sleep 1
        done
    - name: upgrade galera packages
      yum: name={{item}} state=latest
      with_items:
        - "*mariadb*"
        - "*galera*"
    - name: reload systemd
      command: systemctl daemon-reload
    - name: allow galera to run on this node
      command: pcs resource clear galera-master
    - name: wait for galera to start
      shell: >
        while pcs status xml |
            xmllint --xpath '//resource[@id = "galera" and @role = "Master"]/node[@name="{{crm_node.stdout}}"' -; do
          sleep 1
        done
