# # Upgrade Heat
#
# This playbook updates OpenStack Heat, using the same process that
# we used for Glance.
#
- hosts: controller
  tags:
    - disable
    - disable-heat
  roles:
    - role: pcs-stop-prefix
      resource_prefix: heat
    - role: pcs-stop
      service: heat
      resources:
        - openstack-heat-engine

- hosts: controller
  tags:
    - packages
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - openstack-selinux
        - openstack-heat*
        - python-heat*

- include: reload-systemd.yml

- hosts: controller
  tags:
    - database
  tasks:
    - command: >
        openstack-db --service heat --update
      run_once: true

- hosts: controller
  tags:
    - enable
    - enable-heat
  roles:
    - role: pcs-start-prefix
      resource_prefix: heat
    - role: pcs-start
      service: heat
      resources:
        - openstack-heat-engine
